# Operaciones de matrices con Python

## Multiplicación de matrices

In [ ]:
import numpy as np

In [ ]:
A = np.array([[2,4], [-1,2]])
B = np.array([[3,5],[6,-8]])
np.matmul(A,B)

array([[ 30, -22],
       [  9, -21]])

## Matriz inversa

In [ ]:
Ainverse = np.linalg.inv(A)
Ainverse

array([[ 0.25 , -0.5  ],
       [ 0.125,  0.25 ]])

In [ ]:
np.matmul(A,Ainverse)

array([[1., 0.],
       [0., 1.]])

## Vectores y valores propios

El comando `np.linalg.eig(A)` lo que hace es calcular directamente los valores y vectores propios, llamados values y vectors en el código, respectivamente.

Los vectores que entrega la función np.linalg.eig(A) son vectores columna.

El vector propio correspondiente al valor propio $2$ es $[0.89442719, -0.70710678]$

In [ ]:
A = np.array([[1,2],[1,0]])
values, vectors = np.linalg.eig(A)
values

array([ 2., -1.])

In [ ]:
vectors

array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]])

## Diagonalización

Uno de los hechos más importantes de obtener los vectores y valores propios de una matriz es poder diagonalizarla. En general se define que una matriz A es diagonalizable si es posible escribirla como el producto de: $A = P \cdot D \cdot P^{-1}$. Donde $D$ es una matriz diagonal.

Si una matriz es diagonalizable, la matriz D se construye colocando sus valores propios en la diagonal y la matriz P se construye colocando en cada columna el vector propio,siguiendo el mismo orden de valores propios correspondientes de la matriz $D$.

**Importante**
* Cuando aplicamos este cálculo de vectores y valores propios a una `matriz de covarianza`, los vectores representan las direcciones a lo largo de las cuales percibimos la mayor cantidad de varianza de ese conjunto de datos, donde la cantidad de varianza es proporcional al valor propio de cada vector propio.

Y es importante tener en cuenta que este procedimiento aplica para un conjunto de datos con N variables al que le corresponde una matriz de covarianza de tamaño NxN.

* Para matrices de covarianza, sus vectores propios siempre son independientes unos de otros y esto es justamente lo que queremos en un proceso de reducción de variables, porque direcciones independientes implica que estos vectores representan nuevas variables cuya correlación es la más baja posible y así cada nueva variable es lo más representativa posible.

En álgebra lineal se dice más precisamente que los vectores propios de una matriz de covarianza son ortogonales y esto quiere decir que el producto interno de cualquier par de estos vectores siempre da como resultado cero.

Como consecuencia la matriz se denomina matriz ortogonal, y se sabe en matemáticas que la inversa de una matriz ortogonal es igual a la transpuesta, de manera que: $A = P \cdot D \cdot P^{-1}=P \cdot D \cdot P^{T}$.

## Proyección de un vector:

Vector $a$ proyecta sobre vector $b$:

$$a_{p} = \left( \frac{ a \cdot b }{|b|} \right) \hat{i}$$

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8b8f8c16-0c57-41f8-8529-691d02522b0e' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>